apiVersion: v1
kind: ConfigMap
metadata:
  name: mk3-config
data:
  QDRANT_HOST: "10.20.17.124"
  QDRANT_PORT: "6333"
  NUXT_PUBLIC_API_BASE: "http://mk3.local/api"
  NUXT_API_BASE_SERVER: "http://mk3-api:8001"
  CORS_ORIGINS: "[\"http://mk2.local\"]"
  AUTH_SERVICE_URL: "http://mk2-auth.pos-mk2.svc.cluster.local:3002"
  S3_BUCKET: "jsh-ai-dev-s3-bucket"
  S3_PREFIX: "pos-mk3-import-data"
  AWS_REGION: "ap-northeast-2"
