apiVersion: v1
kind: ConfigMap
metadata:
  name: mk3-config
data:
  QDRANT_HOST: "10.20.17.124"
  QDRANT_PORT: "6333"
  NUXT_PUBLIC_API_BASE: "https://mk3.REPLACE_DOMAIN/api"
  NUXT_API_BASE_SERVER: "http://mk3-api:8001"
  CORS_ORIGINS: "[\"https://mk2.REPLACE_DOMAIN\"]"
  AUTH_SERVICE_URL: "http://mk2-auth.pos-mk2.svc.cluster.local:3002"
