apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pos-mk3

resources:
  - ../../base/namespace.yaml
  - ../../base/configmap.yaml
  - ../../base/api.yaml
  - ../../base/web.yaml
  - ../../base/ingress.yaml
  - secret.aws.yaml

patches:
  - path: configmap.aws.patch.yaml
  - path: ingress.aws.patch.yaml

images:
  - name: personal-operating-system-mk3-api
    newName: 948360715051.dkr.ecr.ap-northeast-2.amazonaws.com/personal-operating-system-mk3-api
    newTag: latest
  - name: personal-operating-system-mk3-web
    newName: 948360715051.dkr.ecr.ap-northeast-2.amazonaws.com/personal-operating-system-mk3-web
    newTag: latest
