apiVersion: v1
kind: Secret
metadata:
  name: mk3-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "pos"
  MONGO_INITDB_ROOT_PASSWORD: "REPLACE_MONGO_PASSWORD"
  MONGODB_URL: "mongodb://pos:REPLACE_MONGO_PASSWORD@REPLACE_MONGO_ENDPOINT:27017"
  QDRANT_API_KEY: "REPLACE_QDRANT_API_KEY"
  OPENAI_API_KEY: "REPLACE_OPENAI_API_KEY"
  GEMINI_API_KEY: "REPLACE_GEMINI_API_KEY"
  ANTHROPIC_API_KEY: "REPLACE_ANTHROPIC_API_KEY"
