apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mk3-ingress
spec:
  rules:
    - host: mk3.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mk3-app
                port:
                  number: 8001
