apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pos-mk3

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongodb.yaml
  - qdrant.yaml
  - api.yaml
  - ingress.yaml
