apiVersion: v1
kind: Secret
metadata:
  name: mk3-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "pos"
  MONGO_INITDB_ROOT_PASSWORD: "pos"
  MONGODB_URL: "mongodb://pos:pos@mk3-mongodb:27017"
  QDRANT_API_KEY: ""
  OPENAI_API_KEY: ""
  GEMINI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
